@echo off
setlocal enabledelayedexpansion

echo Running Kubernetes Pipelines for Robotics BDD Simulation Tests...
echo Author: Bang Thien Nguyen, ontario1998@gmail.com
echo.

:: -----------------------------------------------------------
:: ARGUMENT CHECKING & SETUP
:: -----------------------------------------------------------

:: Check for required BUILD_NUMBER (%1)
if "%1"=="" (
echo.
echo ERROR: Missing required argument BUILD_NUMBER.
echo Usage: %~n0 <BUILD_NUMBER> [SUITE_MARKER]
echo Example: %~n0 1 pick
exit /b 1
)

set BUILD_NUMBER=%1
set SUITE_MARKER=%2
set IMAGE_ID_FILE=python_image_id.tmp
set REPORT_IMAGE_TAG=luckyjoy/robotics-bdd-report
set ALLURE_REPORT_DIR=reports\allure-report

:: Set default SUITE_MARKER if not provided
if "%SUITE_MARKER%"=="" (
set SUITE_MARKER=all
echo Defaulting SUITE_MARKER to '%SUITE_MARKER%'.
)

echo.
echo =======================================================
echo STARTING ORCHESTRATION PIPELINE
echo Build Number: %BUILD_NUMBER%
echo Test Suite:   %SUITE_MARKER%
echo =======================================================

:: -----------------------------------------------------------
:: STEP 1: Skipping local image tag removal
:: -----------------------------------------------------------
echo.
echo [STEP 1/10] Skipping local image tag removal for performance.

:: -----------------------------------------------------------
:: STEP 2: Run Python workflow (Build BDD image, Run Tests, Generate Reports)
:: -----------------------------------------------------------
echo.
echo [STEP 2/10] Running Python workflow (Build BDD Image, Run Tests, Generate Reports)...
echo Executing command: python run_kubenestes.py %BUILD_NUMBER% %SUITE_MARKER%
python run_kubenestes.py %BUILD_NUMBER% %SUITE_MARKER%
if %ERRORLEVEL% neq 0 goto python_error

:: Retrieve the image ID generated by the Python script
set LOCAL_IMAGE_ID=
if exist %IMAGE_ID_FILE% (
    set /p LOCAL_IMAGE_ID=< %IMAGE_ID_FILE%
    del %IMAGE_ID_FILE%
)

echo Python script completed successfully. New image built (if required) and reports generated locally.
goto continue_pipeline

:python_error
echo.
echo CRITICAL ERROR: Python script failed during image build or test run. Exiting.
:: Clean up temp file if it exists
if exist %IMAGE_ID_FILE% del %IMAGE_ID_FILE%
exit /b %ERRORLEVEL%

:continue_pipeline
:: -----------------------------------------------------------
:: STEP 3: Build and Push Allure Report Image to Docker Hub.
:: This step publishes the static report files as a lightweight Docker image.
:: -----------------------------------------------------------
echo.
echo [STEP 3/10] Building and Pushing Report Hosting Image to Docker Hub...
set REPORT_FULL_TAG=%REPORT_IMAGE_TAG%:%BUILD_NUMBER%

:: Check if the report directory contains the generated Dockerfile
if not exist %ALLURE_REPORT_DIR%\Dockerfile (
    echo.
    echo CRITICAL ERROR: Report Dockerfile not found in %ALLURE_REPORT_DIR%. Cannot publish report.
    exit /b 1
)

echo Executing command: docker build -t %REPORT_FULL_TAG% %ALLURE_REPORT_DIR%
docker build -t %REPORT_FULL_TAG% %ALLURE_REPORT_DIR%
if %ERRORLEVEL% neq 0 (
    echo CRITICAL ERROR: Docker report image build failed. Exiting.
    exit /b %ERRORLEVEL%
)

echo Executing command: docker push %REPORT_FULL_TAG%
docker push %REPORT_FULL_TAG%
if %ERRORLEVEL% neq 0 (
    echo CRITICAL ERROR: Docker report image push failed. Check 'docker login' status. Exiting.
    exit /b %ERRORLEVEL%
)
echo ✅ Report Image pushed successfully to Docker Hub.
echo.

:: -----------------------------------------------------------
:: STEP 4: Delete any previous running Kubernetes Job. (Old Step 3)
:: -----------------------------------------------------------
echo.
echo [STEP 4/10] Deleting previous Kubernetes Job (if found)...
echo Executing command: kubectl delete job robotics-bdd-test-run --ignore-not-found=true
kubectl delete job robotics-bdd-test-run --ignore-not-found=true
echo Previous job deleted (or was not found).

:: -----------------------------------------------------------
:: STEP 5: Apply the Kubernetes Job definition. (Old Step 4)
:: -----------------------------------------------------------
echo.
echo [STEP 5/10] Applying new Kubernetes Job definition (robotics-bdd-job.yaml)...
echo Executing command: kubectl apply -f robotics-bdd-job.yaml
kubectl apply -f robotics-bdd-job.yaml
if %ERRORLEVEL% neq 0 (
echo.
echo CRITICAL ERROR: kubectl apply failed. Is Kubernetes running? Exiting.
exit /b %ERRORLEVEL%
)
echo Kubernetes Job applied successfully.

:: -----------------------------------------------------------
:: STEP 6: Check the status of the new Pods created by the Job. (Old Step 5)
:: -----------------------------------------------------------
echo.
echo [STEP 6/10] Checking status of robotics-bdd Pods...
echo Executing command: kubectl get pods -l app=robotics-bdd
kubectl get pods -l app=robotics-bdd

:: -----------------------------------------------------------
:: STEP 7: Tag the local image with the fully qualified name. (Old Step 6)
:: -----------------------------------------------------------
echo.
echo [STEP 7/10] Ensuring BDD Test image is tagged for push...
echo Executing command: docker tag luckyjoy/robotics-bdd-local:latest luckyjoy/robotics-bdd-local:latest
docker tag luckyjoy/robotics-bdd-local:latest luckyjoy/robotics-bdd-local:latest
if %ERRORLEVEL% neq 0 (
echo CRITICAL ERROR: Docker tagging failed. Exiting.
exit /b %ERRORLEVEL%
)
echo Image tagged correctly.

:: -----------------------------------------------------------
:: STEP 8: Conditional Push the updated BDD image to Docker Hub. (Old Step 7)
:: -----------------------------------------------------------
echo.
echo [STEP 8/10] Pushing BDD Test Image to Docker Hub (Conditional)...

set LAST_ID_FILE=last_pushed_id.txt
set LAST_PUSHED_ID=

:: Get last pushed ID from file
if exist %LAST_ID_FILE% (
    set /p LAST_PUSHED_ID=< %LAST_ID_FILE%
) else (
    set LAST_PUSHED_ID=
)

if "!LOCAL_IMAGE_ID!"=="" (
    echo.
    echo WARNING: Could not retrieve local image ID. Proceeding with push just in case.
    goto forced_push
)

if "!LOCAL_IMAGE_ID!"=="!LAST_PUSHED_ID!" (
    echo.
    echo ✅ Local image ID matches last pushed ID. Skipping Docker Hub push for performance.
    goto skip_push
)

:forced_push
echo.
echo Local image ID has changed or file not found. Pushing image...
echo Executing command: docker push luckyjoy/robotics-bdd-local:latest
docker push luckyjoy/robotics-bdd-local:latest
if %ERRORLEVEL% neq 0 (
    echo CRITICAL ERROR: Docker push failed. Check 'docker login' status. Exiting.
    exit /b %ERRORLEVEL%
)

:: Save the new ID
echo !LOCAL_IMAGE_ID!> %LAST_ID_FILE%
echo Image pushed successfully to Docker Hub and new ID saved.
goto push_complete

:skip_push
echo.
echo Push skipped.

:push_complete
:: -----------------------------------------------------------
:: STEP 9: Monitor Test Execution (Automation Improvement) (Old Step 8)
:: -----------------------------------------------------------
echo.
echo [STEP 9/10] Streaming Kubernetes Job Logs... (Press Ctrl+C to stop stream)
echo Executing command: Dynamically finding and streaming logs from latest Pod...
FOR /F "tokens=*" %%p IN ('kubectl get pods -l app=robotics-bdd --sort-by=.metadata.creationTimestamp -o jsonpath="{.items[0].metadata.name}" 2^>NUL') DO kubectl logs -f %%p

:: -----------------------------------------------------------
:: FINAL STATUS
:: -----------------------------------------------------------
echo.
echo ====================================================================
echo PIPELINE COMPLETE.
echo Kubernetes Job execution has finished.
echo Use 'debug_job.bat' to inspect final Pod status if the logs above did not appear.
echo ====================================================================
echo.
echo BDD Test Image Location: https://hub.docker.com/r/luckyjoy/robotics-bdd-local/tags
echo Report Artifact Tag: %REPORT_FULL_TAG%
echo Report Hub Link: https://hub.docker.com/r/%REPORT_IMAGE_TAG%/tags
echo Report Artifact FQDN: docker.io/%REPORT_FULL_TAG%
echo.
echo --- Deployment for Remote Viewing ---
echo The report is packaged in a lightweight web server image pushed to Docker Hub.
echo To view it remotely, you must run this image on a publicly accessible server (VM or cloud service)
echo and ensure port 80 is publicly exposed through the server's firewall.
echo.
echo 1. SSH into your remote server/VM.
echo 2. Run the image, mapping the port:
echo    docker run -d -p 80:80 docker.io/%REPORT_FULL_TAG%
echo 3. Access the report via your server's public IP address or DNS name.
echo ---------------------------------------------------------------------
echo.

:: -----------------------------------------------------------
:: STEP 10: Docker Cleanup (Old Step 9)
:: -----------------------------------------------------------
echo.
echo [STEP 10/10] Starting Docker resource cleanup...
echo Executing command: docker container prune -f
docker container prune -f
echo Executing command: docker network prune -f
docker network prune -f

echo Image 'luckyjoy/robotics-bdd-local:latest' is intentionally kept locally for performance on next run.

endlocal
