[build]
# Defines the starting directory for the build process (repository root)
base = "."

# Skip Docker execution in Netlify — only package and deploy static files
command = "mkdir -p dist && cp index.html dist/ && cp _redirects dist/ && cp -r reports dist/"

# This specifies that ONLY the contents of 'dist' will be deployed publicly
publish = "dist"

[functions]
# Defines the directory for serverless functions (optional)
directory = "netlify/functions"
