[build]
base = "."
The build command creates a 'dist' folder and copies all necessary static assets into it.

command = "mkdir -p dist && cp index.html dist/ && cp _redirects dist/ && cp -r reports dist/"
This specifies that ONLY the contents of 'dist' will be deployed publicly.

publish = "dist"

[functions]
directory = "netlify/functions"