apiVersion: batch/v1
kind: Job
metadata:
  name: robotics-bdd-test-run
  labels:
    app: robotics-bdd
spec:
  # The job will retry up to 2 times if the Pod fails (Backoff Limit)
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: robotics-bdd
    spec:
      restartPolicy: OnFailure
      containers:
        - name: bdd-runner
          # Your Docker Hub image
          image: luckyjoy/robotics-bdd-local:latest 
          
          # FIX: imagePullPolicy must be inside the container spec
          imagePullPolicy: Always 
          
          # The command to execute the run_kubenestes.py script
          # The entrypoint is 'python'
          command: ["python"]
          args:
            - "run_kubenestes.py"  # sys.argv[0] is the script name
            - "1"                  # sys.argv[1]: The Build Number
            - "pick"               # sys.argv[2]: The SUITE_MARKER (e.g., 'pick', 'navigation', etc.)
            
          # The script saves output files to the /app directory
          workingDir: /app
          
          # Mount the PVC at /app
          volumeMounts:
            - name: allure-data
              mountPath: /app

      # Define the Persistent Volume Claim
      volumes:
        - name: allure-data
          persistentVolumeClaim:
            claimName: robotics-bdd-pvc